const task11 = {
  id: 'task-1-1',
  domain: 'domain-1',
  domainLabel: 'Domain 1',
  domainColor: '#E8881A',
  title: 'Task 1.1: Perform data ingestion',

  knowledge: [
    {
      topic: 'Throughput and latency characteristics for AWS services that ingest data',
      heading: 'Throughput e Latência em Serviços de Ingestão da AWS',
      what: 'Throughput é a quantidade de dados que um serviço consegue processar por unidade de tempo (ex: MB/s, registros/s). Latência é o tempo que um dado leva desde que entra no sistema até estar disponível para leitura ou processamento. São as duas métricas fundamentais para escolher o serviço certo de ingestão.',
      how: 'Cada serviço AWS tem um modelo interno diferente. O Kinesis Data Streams, por exemplo, opera com shards: cada shard suporta 1 MB/s de entrada e 2 MB/s de saída, com latência de milissegundos. O S3, por outro lado, não tem latência garantida porque é um sistema de armazenamento de objetos, não um stream. O SQS tem throughput praticamente ilimitado mas latência na casa dos milissegundos a segundos dependendo do polling. O DynamoDB Streams replica alterações com latência geralmente abaixo de 24 horas, mas tipicamente em segundos.',
      characteristics: [
        'Kinesis: até 1 MB/s por shard de entrada, 2 MB/s de saída, retenção padrão de 24 horas (até 365 dias)',
        'MSK (Kafka gerenciado): throughput muito alto, configurável por número de brokers e partições, latência baixa',
        'SQS Standard: throughput ilimitado, entrega at-least-once, sem garantia de ordem',
        'SQS FIFO: até 3.000 mensagens/s com batching',
        'Firehose: sem shards, escala automaticamente, mas tem latência mínima de buffer (60 segundos ou 1 MB por padrão)',
      ],
      differentiation: 'A principal distinção é entre serviços de baixa latência e alto throughput para streaming (Kinesis, MSK) versus serviços de alta durabilidade e throughput assíncrono para batch (S3, Glue, EMR). O Firehose fica no meio: é streaming, mas introduz um buffer proposital antes de entregar ao destino.',
    },
    {
      topic: 'Data ingestion patterns (for example, frequency and data history)',
      heading: 'Padrões de Ingestão de Dados',
      what: 'São as formas arquiteturais de como dados chegam a um sistema. O padrão define frequência, volume por ciclo, e se há histórico acumulado ou apenas dados recentes.',
      how: 'Os dois grandes eixos são: frequência (contínua vs periódica) e volume por ciclo (micro-lotes vs grandes lotes). Um pipeline pode ingerir dados a cada evento individual (streaming puro), a cada minuto (micro-batch), a cada hora ou dia (batch tradicional), ou apenas uma vez com carga histórica (full load inicial).',
      characteristics: [
        'Ingestão histórica (backfill): carrega dados passados de uma vez, geralmente via DMS ou Glue de uma fonte relacional para S3/Redshift',
        'Ingestão incremental: captura apenas o que mudou desde a última execução, usando colunas de timestamp ou CDC (Change Data Capture)',
        'Ingestão por evento: dispara quando algo acontece no sistema de origem, sem periodicidade fixa',
      ],
      differentiation: 'Full load vs incremental é a distinção mais importante. Full load é simples mas caro em escala. Incremental é eficiente mas exige que a fonte suporte algum mecanismo de rastreamento de mudanças (timestamp, sequência, CDC via DMS ou DynamoDB Streams).',
    },
    {
      topic: 'Streaming data ingestion',
      heading: 'Streaming Data Ingestion',
      what: 'Ingestão de dados em fluxo contínuo, onde os registros são processados individualmente ou em micro-lotes com latência muito baixa, geralmente milissegundos a segundos.',
      how: 'Um produtor publica registros continuamente em um canal (shard no Kinesis, partição no Kafka). Um consumidor lê esses registros quase em tempo real. O sistema mantém os dados disponíveis por um período de retenção (no Kinesis, de 24h a 365 dias), permitindo que múltiplos consumidores leiam de forma independente.',
      characteristics: [
        'Baixa latência é a característica central — dados disponíveis para leitura em segundos ou menos',
        'Há sempre um conceito de sequência ou offset que permite rastrear onde o consumidor parou',
        'A ordem pode ser garantida dentro de uma partição/shard, mas não entre partições diferentes',
      ],
      differentiation: 'Streaming se diferencia do batch principalmente pela continuidade: não há um "arquivo" gerado — há um fluxo. O consumidor deve estar preparado para processar dados que chegam a qualquer momento, sem saber quando o lote termina (porque não termina).',
    },
    {
      topic: 'Batch data ingestion (for example, scheduled ingestion, event-driven ingestion)',
      heading: 'Batch Data Ingestion',
      what: 'Ingestão em que os dados são coletados e processados em grupos discretos, em intervalos definidos (agendados) ou disparados por um evento (event-driven).',
      how: 'No modo agendado, um job é executado em horários fixos (ex: todo dia às 2h da manhã) e processa todos os dados acumulados desde a última execução. No modo event-driven, algo externo dispara o job: um arquivo chegar ao S3, uma fila atingir certo volume, ou uma mudança em banco de dados.',
      characteristics: [
        'Latência alta é inerente ao batch — os dados ficam represados até o próximo ciclo',
        'O custo por dado processado tende a ser menor, pois há menos overhead de gerenciamento',
        'Volumes por ciclo costumam ser grandes',
        'Reprocessamento é mais simples, pois os dados de entrada ficam armazenados e podem ser relidos',
      ],
      differentiation: 'Batch agendado vs event-driven: no agendado, o clock define quando processar; no event-driven, o dado define. Event-driven é mais responsivo, mas exige infraestrutura de gatilho (S3 Event Notifications, EventBridge, SQS).',
    },
    {
      topic: 'Replayability of data ingestion pipelines',
      heading: 'Replayability de Pipelines de Ingestão',
      what: 'A capacidade de reprocessar dados passados — seja porque houve um erro, uma mudança de lógica, ou a necessidade de preencher um período ausente. Um pipeline replayable pode ser executado novamente sobre os mesmos dados de entrada e produzir o resultado correto.',
      how: 'Para ser replayable, o pipeline precisa de dados de entrada duráveis e imutáveis (ex: S3 como fonte permanente) e processamento idempotente (rodar duas vezes produz o mesmo resultado que rodar uma vez). No streaming, o Kinesis e o MSK permitem replay enquanto os dados estão dentro do período de retenção. Após esse período, o replay só é possível se os dados foram arquivados (ex: Firehose → S3).',
      characteristics: [
        'Pipelines baseados em S3 são naturalmente replayable porque o arquivo original permanece',
        'Pipelines baseados em streaming têm replayability limitada pela janela de retenção',
        'CDC com DMS pode ser replayable se os logs binários da fonte ainda existirem',
        'Idempotência do processamento é o requisito complementar do lado do consumidor',
      ],
      differentiation: 'A diferença está entre sistemas de retenção efêmera (SQS apaga a mensagem após o consumo) e sistemas de retenção persistente (Kinesis, S3, MSK com retenção longa). Para garantir replay, a fonte deve ser durável e o consumidor deve rastrear seu próprio offset/posição.',
    },
    {
      topic: 'Stateful and stateless data transactions',
      heading: 'Transações Stateful e Stateless',
      what: 'Stateless significa que cada operação de processamento é independente — o sistema não precisa lembrar nada de operações anteriores para processar a atual. Stateful significa que o resultado de processar um dado depende de dados anteriores ou de um estado acumulado.',
      how: 'Um processador stateless recebe um registro, aplica uma transformação pura, e emite um resultado — sem consultar nada do passado. Um processador stateful mantém algum tipo de estado (contagem, janela de tempo, agregação, sessão de usuário) que é atualizado a cada novo registro e influencia o resultado futuro.',
      characteristics: [
        'Stateless: simples de escalar horizontalmente, sem necessidade de coordenação entre workers, fácil de reprocessar',
        'Stateful: requer um mecanismo de armazenamento de estado (ex: DynamoDB, Redis, RocksDB no Flink)',
        'Stateful: mais complexo, mais caro, e exige cuidado no reprocessamento para não corromper o estado acumulado',
      ],
      differentiation: 'Lambda functions são o exemplo clássico de processamento stateless na AWS: cada invocação é independente. Kinesis Data Analytics (Apache Flink) é o exemplo de processamento stateful: ele mantém janelas de agregação, sessões, e contagens ao longo do tempo.',
    },
  ],

  skills: [
    {
      topic: 'Reading data from streaming sources (Amazon Kinesis, Amazon MSK, DynamoDB Streams, AWS DMS, AWS Glue, Amazon Redshift)',
      heading: 'Leitura de Dados de Fontes Streaming',
      problem: 'Consumir dados em tempo real de sistemas que publicam eventos continuamente — filas de mensagens, streams de cliques, alterações em banco de dados — para processar, transformar, ou carregar com baixa latência.',
      keywords: '"tempo real", "baixa latência", "fluxo contínuo", "eventos", "CDC", "alterações em banco de dados", "Kinesis", "MSK", "DynamoDB Streams", "DMS".',
      whyNot: 'S3 não serve para leitura em tempo real — ele é armazenamento de objetos, sem mecanismo de push. Glue Jobs são batch por natureza, não consomem streams continuamente. Para streaming real, as opções são Kinesis (Data Streams ou Analytics), MSK, DynamoDB Streams, ou DMS em modo CDC.',
      scenario: '"Uma aplicação de e-commerce precisa detectar fraudes em menos de 1 segundo após cada transação. Os dados de transação chegam continuamente. Qual arquitetura usar?" → Kinesis Data Streams como ingestão + Lambda ou Kinesis Data Analytics para processamento em tempo real.',
    },
    {
      topic: 'Reading data from batch sources (Amazon S3, AWS Glue, Amazon EMR, AWS DMS, Amazon Redshift, AWS Lambda, Amazon AppFlow)',
      heading: 'Leitura de Dados de Fontes Batch',
      problem: 'Processar grandes volumes de dados históricos ou acumulados que estão armazenados em sistemas como S3, bancos relacionais, ou data warehouses — sem necessidade de baixa latência.',
      keywords: '"agendado", "diário", "semanal", "histórico", "arquivo", "ETL", "S3", "Glue", "EMR", "Redshift", "AppFlow", "migração de banco de dados".',
      whyNot: 'Kinesis não é adequado para ler dados históricos armazenados em S3 — ele é para streams ativos. Lambda tem limite de 15 minutos de execução e não escala bem para volumes massivos. Para batch pesado, Glue ou EMR são as escolhas certas.',
      scenario: '"Uma empresa precisa processar logs de acesso armazenados no S3, transformá-los e carregá-los no Redshift todo dia às 3h da manhã. Qual serviço orquestra isso?" → AWS Glue Job agendado via EventBridge Scheduler ou Glue Trigger.',
    },
    {
      topic: 'Implementing appropriate configuration options for batch ingestion',
      heading: 'Configurações de Ingestão Batch',
      problem: 'Ajustar parâmetros de jobs batch para equilibrar custo, performance e janela de processamento — como tamanho de partição, paralelismo, formato de arquivo, e compressão.',
      keywords: '"otimizar custo", "performance de ETL", "paralelismo", "particionamento", "formato Parquet", "compressão", "DPU", "worker type".',
      whyNot: 'Configurar um Lambda para processar um arquivo de 100 GB não funciona — o Lambda tem limite de memória e tempo. Glue ou EMR são os serviços que permitem configurar workers, memória, paralelismo e formato de saída adequadamente para volumes grandes.',
      scenario: '"Um Glue Job está demorando 4 horas para processar dados diários. Como reduzir o tempo?" → Aumentar o número de DPUs, usar formato Parquet com particionamento adequado, habilitar pushdown predicates.',
    },
    {
      topic: 'Consuming data APIs',
      heading: 'Consumo de APIs de Dados',
      problem: 'Ingerir dados de sistemas externos (SaaS, parceiros, APIs REST/GraphQL) que não têm conectores nativos AWS, precisando de chamadas HTTP periódicas ou contínuas.',
      keywords: '"API REST", "SaaS", "Salesforce", "terceiros", "OAuth", "paginação", "rate limit", "AppFlow".',
      whyNot: 'Glue não tem conectores nativos para APIs REST arbitrárias. A solução mais comum é Lambda (para chamadas simples e periódicas) ou AppFlow (para SaaS com conectores pré-construídos como Salesforce, SAP, ServiceNow). Para APIs com rate limits agressivos, Lambda com retry e backoff exponencial é necessário.',
      scenario: '"Uma empresa quer ingerir dados do Salesforce diariamente no S3. Qual serviço usar?" → Amazon AppFlow, que tem conector nativo para Salesforce e pode exportar direto para S3.',
    },
    {
      topic: 'Setting up schedulers by using Amazon EventBridge, Apache Airflow, or time-based schedules for jobs and crawlers',
      heading: 'Agendadores: EventBridge, Airflow e Time-based Schedules',
      problem: 'Disparar jobs, crawlers, e pipelines em horários definidos ou com expressões de recorrência (cron), de forma confiável e desacoplada da lógica de processamento.',
      keywords: '"agendar", "cron", "todo dia", "toda hora", "orquestração", "EventBridge Scheduler", "MWAA", "Airflow", "Glue Trigger", "horário fixo".',
      whyNot: 'Step Functions por si só não agenda — precisa de um trigger externo. CloudWatch Events foi substituído pelo EventBridge. Para orquestração complexa com dependências entre tasks, Airflow (MWAA) é mais adequado que EventBridge puro, que é melhor para triggers simples.',
      scenario: '"Um Glue Job deve executar todo dia às 2h UTC. Qual a forma mais simples de agendar?" → EventBridge Scheduler com expressão cron(0 2 * * ? *) apontando para o Glue Job.',
    },
    {
      topic: 'Setting up event triggers (for example, Amazon S3 Event Notifications, EventBridge)',
      heading: 'Event Triggers: S3 Event Notifications e EventBridge',
      problem: 'Disparar processamento automaticamente quando algo acontece — um arquivo chega ao S3, um estado muda em um serviço AWS — sem precisar de polling periódico.',
      keywords: '"quando um arquivo chegar", "event-driven", "trigger automático", "S3 Event Notification", "put object", "reage a eventos", "desacoplado".',
      whyNot: 'Polling via Lambda agendada é ineficiente e tem latência. S3 Event Notifications são instantâneas e disparam Lambda ou SQS no momento do upload. EventBridge é mais poderoso para eventos de múltiplos serviços AWS e permite filtros sofisticados por conteúdo do evento.',
      scenario: '"Toda vez que um arquivo CSV chega em um bucket S3, um processo deve transformá-lo e salvar em outro bucket. Qual arquitetura?" → S3 Event Notification → Lambda → S3 destino. Ou S3 Event Notification → SQS → Lambda (com fila para desacoplar e garantir processamento).',
    },
    {
      topic: 'Calling a Lambda function from Amazon Kinesis',
      heading: 'Chamando Lambda a partir do Kinesis',
      problem: 'Processar cada lote de registros de um stream Kinesis com lógica customizada em Python ou outro runtime, sem precisar gerenciar infraestrutura de consumidores.',
      keywords: '"processar stream", "Kinesis trigger", "event source mapping", "Lambda consumer", "batch size", "starting position".',
      whyNot: 'Kinesis Data Analytics é mais adequado para processamento stateful ou com SQL. Lambda é a escolha quando a lógica é simples, stateless, e pode ser implementada em uma função. A integração é via Event Source Mapping — o Lambda polling o shard automaticamente, sem precisar de código de polling manual.',
      scenario: '"Registros chegam no Kinesis Data Streams e precisam ser filtrados e inseridos no DynamoDB. Qual é a arquitetura serverless mais simples?" → Event Source Mapping conectando o Kinesis stream ao Lambda, com batch size configurável.',
    },
    {
      topic: 'Creating allowlists for IP addresses to allow connections to data sources',
      heading: 'Allowlists de IP para Conexões a Fontes de Dados',
      problem: 'Permitir que serviços AWS (Glue, DMS, Lambda em VPC) se conectem a bancos de dados on-premises ou em outras contas que têm firewall restritivo por IP de origem.',
      keywords: '"firewall", "whitelist", "IP fixo", "banco on-premises", "conexão bloqueada", "NAT Gateway", "Elastic IP".',
      whyNot: 'Lambda sem VPC tem IPs dinâmicos — impossível fazer allowlist estático. Lambda em VPC com NAT Gateway tem IPs fixos (Elastic IPs do NAT). Glue dentro de VPC também pode usar NAT Gateway para ter IP de saída previsível. A solução sempre envolve colocar o recurso em uma VPC com NAT Gateway e adicionar o Elastic IP do NAT ao allowlist da fonte.',
      scenario: '"Um Glue Job precisa se conectar a um banco MySQL on-premises que só aceita conexões de IPs específicos. O que fazer?" → Configurar Glue para rodar dentro de uma VPC, usar NAT Gateway com Elastic IP, e adicionar esse IP ao allowlist do firewall on-premises.',
    },
    {
      topic: 'Implementing throttling and overcoming rate limits (for example, DynamoDB, Amazon RDS, Kinesis)',
      heading: 'Throttling e Rate Limits',
      problem: 'Evitar que um pipeline falhe ou seja bloqueado quando acessa serviços que têm limites de requisições por segundo — DynamoDB, RDS, Kinesis, APIs externas.',
      keywords: '"ProvisionedThroughputExceededException", "ThrottlingException", "rate limit", "429", "backoff", "retry", "capacidade provisionada", "WCU/RCU", "shard limit".',
      whyNot: 'Aumentar a capacidade provisionada resolve o sintoma mas pode ser caro. A solução correta depende da causa: se é DynamoDB, usar on-demand mode ou aumentar WCU/RCU; se é Kinesis, aumentar shards ou usar Enhanced Fan-Out; se é uma API externa, implementar exponential backoff com jitter no código do consumidor.',
      scenario: '"Um job Glue lendo do DynamoDB está recebendo erros de ProvisionedThroughputExceededException. Como resolver sem aumentar custos?" → Configurar o job para usar o modo paralelo com throttling controlado, ou usar DynamoDB Streams ao invés de scan direto na tabela.',
    },
    {
      topic: 'Managing fan-in and fan-out for streaming data distribution',
      heading: 'Fan-in e Fan-out em Streaming',
      problem: 'Distribuir um stream para múltiplos consumidores (fan-out) ou agregar múltiplos streams em um único destino (fan-in), mantendo performance e isolamento entre consumidores.',
      keywords: '"múltiplos consumidores", "isolamento de consumo", "Enhanced Fan-Out", "SNS + SQS", "fan-out", "consolidar streams", "múltiplas fontes".',
      whyNot: 'No Kinesis padrão (shared throughput), múltiplos consumidores competem pelos mesmos 2 MB/s por shard. Com Enhanced Fan-Out, cada consumidor registrado recebe seus próprios 2 MB/s de forma independente. Para fan-in, múltiplos produtores podem escrever no mesmo stream ou usar um tópico SNS que distribui para múltiplos SQS.',
      scenario: '"Três aplicações diferentes precisam consumir o mesmo stream Kinesis de forma independente, cada uma sem impactar a performance das outras. Qual configuração usar?" → Registrar cada consumidor com Kinesis Enhanced Fan-Out (RegisterStreamConsumer), garantindo throughput dedicado de 2 MB/s por consumidor por shard.',
    },
  ],
}

export default task11
